### ISSUE TITLE
Refresh button breaking (Ian only for some reason) error provided tho

### ISSUE THREAD

**Issue by BirdInAHat** [collinjones/bandnames.cool#19]
![99de8bad0540954c30073a6bf11f2ba3](https://github.com/collinjones/bandnames.cool/assets/112828811/d8092c6a-fc64-498d-8468-f170c5050d2d)

**Comment by collinjones** [comment]
The issue is the code that checks whether the user is on the homepage or not (used to prevent bug when clicking on .cool on any page other than homepage).

Removing that piece of checking code fixes it, but introduces the bug back to pages that aren't the homepage.

**Comment by collinjones** [comment]
The reason is due to the code that checks which page the request is coming from. Still unsure how to fix.

**Comment by collinjones** [comment]
Fixed
